const base="Innovative%20Product%20Development/My%20Projects/";
const data=[
["Bionic Quadruped Robot Dog","AI","Robotics · Embedded systems","A high-performance 12-DOF robot built for movement in three-dimensional space, combining Jetson compute, STM32 control, LiDAR SLAM, and CAN-connected brushless joints.","Jetson Orin NX,ROS 2,STM32H750,LiDAR SLAM,CAN","Bionic%20Quadruped%20Robot%20Dog/RoboticDog.jpg","Bionic%20Quadruped%20Robot%20Dog.html"],
["Outdoor Air Quality Monitoring","IoT","Environmental IoT","A connected air-quality platform combining accurate sensing, long-range and cellular connectivity, mobile software, and comprehensive cloud data access.","ESP-IDF,Altium Designer,LoRaWAN,4G/LTE,React Native,AWS","Outdoor%20Air%20Quality%20Monitoring%20System/Prana_Air_Monitor_example.png","Outdoor%20Air%20Quality%20Monitoring%20System.html"],
["Medical Vibration Gloves","Firmware","Medical wearable","A wearable neurostimulation system that generates programmable vibration profiles for Parkinson’s therapy research on a low-power Bluetooth platform.","nRF5340,Zephyr RTOS,PWM,Bluetooth LE,PCB Design","Medical%20Vibration%20Gloves/gloves-1.webp","Medical%20Vibration%20Gloves.html"],
["CAN Network Vehicle Terminal","IoT","Automotive · Cloud","An STM32 and LTE vehicle terminal with customizable CAN decoding, GPS positioning, offline storage, MQTT communication, and OTA firmware upgrades.","STM32,LTE,GNSS,CAN bus,MQTT,AWS IoT","CAN%20Network%20Vehicle%20Terminal/cover.png","CAN%20Network%20Vehicle%20Terminal.html"],
["SmartWatch Development","Firmware","Consumer wearable","An STM32 smartwatch integrating a graphical interface, wireless updates, motion and environmental sensors, heart-rate monitoring, NFC, and Bluetooth.","STM32F411,FreeRTOS,LVGL,NFC,Bluetooth","SmartWatch%20Development/ddf1a086b35f4ca1a899baa657901bbb.jpg","SmartWatch%20Development.html"],
["Indoor Farm AI Monitoring","AI","AgTech · Computer vision","An intelligent crop monitoring system combining multispectral imaging with growing-condition data and AI to optimize indoor farms.","Multispectral imaging,Edge AI,IoT,Cloud analytics","Indoor%20Farm%20AI-Powered%20Monitoring%20System/Ecobloom.png","Indoor%20Farm%20AI-Powered%20Monitoring%20System.html"],
["3-Phase Power Monitoring Sensor","Hardware","Energy · Wireless sensing","A custom sensor for accurate power-quality analysis and fault detection with local logging and gateway-based cloud connectivity.","Altium Designer,Zephyr,Bluetooth Mesh","3-Phase%20Power%20Monitoring%20Sensor/PowerPod.png","3-Phase%20Power%20Monitoring%20Sensor.html"],
["Autopilot Flight Controller","Hardware","Aerospace · Control systems","An ArduPilot-compatible controller engineered for multirotor, fixed-wing, VTOL, ground, surface, and underwater vehicles.","PCB Design,Electronics,Prototyping,Validation","Autopilot%20Flight%20Controller/autopilot.jpg","Autopilot%20Flight%20Controller.html"],
["EchoEar AI Pet","AI","Voice AI · Consumer product","An ESP32-S3 voice-interaction development kit for intelligent toys, speakers, and smart control products backed by large-model services.","ESP32-S3,ESP-IDF,PCB Design,AI integration,3D printing","EchoEar%20-%20ESP32S3-Based%20AI%20Pet/EchoEar.png","EchoEar%20-%20ESP32S3-Based%20AI%20Pet.html"],
["UVC & Ballast Monitoring System","IoT","Industrial monitoring","An ESP32-S3 connected system for monitoring UVC sensors, lamps, and ballasts through a mobile interface and AWS backend.","ESP-IDF,Flutter,AWS","ESP32-S3%20based%20UVC%20&%20Ballast%20Monitoring%20System/ConfluenceAI_UVC_monitor.png","ESP32-S3%20based%20UVC%20&%20Ballast%20Monitoring%20System.html"],
["ESP32-S3 LVGL Touch Screen","Firmware","Embedded HMI","A portrait-format touch display built around the ESP32-S3 with a custom LVGL interface and touch-coordinate handling.","Arduino,ESP32-S3,LVGL,PlatformIO,UI design","ESP32-S3%20LVGL%20Touch%20Screen/esp32-portrait-screen.webp","ESP32-S3%20LVGL%20Touch%20Screen.html"],
["Washing Management Controller","IoT","Commercial control","A rugged i.MX7 control platform with isolated inputs for coin, token, and wash-start systems, paired with cloud connectivity.","Altium Designer,Toradex Yocto,Embedded Linux,AWS","i%20MX7-based%20Washing%20Management%20Controller/ASM-1000_Front_Rear-removebg-preview.png","i%20MX7-based%20Washing%20Management%20Controller.html"],
["Multifunctional Atmosphere Light","Hardware","Connected consumer device","A cylindrical ESP32-C3 product combining rich RGB lighting, audio playback, custom electronics, firmware, and enclosure design.","Altium Designer,ESP-IDF,SolidWorks,3D printing","Multifunctional%20Atmosphere%20Light%20-%20ESP32-C3/cover.jpg","Multifunctional%20Atmosphere%20Light%20-%20ESP32-C3.html"],
["Bluetooth–Cellular Gateway","IoT","Asset tracking · Cloud","A Nordic-based gateway transferring real-time data from Bluetooth Mesh sensors to AWS over cellular networks.","Nordic SoC,Zephyr,Bluetooth Mesh,Cellular,AWS IoT","Nordic%20SoC%20Bluetooth-Cellular%20Gateway/GearTrak_01_BLK.jpg","Nordic%20SoC%20Bluetooth-Cellular%20Gateway.html"],
["Raspberry Pi Sauna Controller","IoT","Smart appliance","A commercial-grade CM4 controller with a custom carrier board and kiosk application for live sauna control and monitoring.","Raspberry Pi CM4,PCB Design,Python,Flask,Kiosk UI","Raspberry%20Pi%20Sauna%20Controller/Sauna_IoT_System.png","Raspberry%20Pi%20Sauna%20Controller.html"],
["RK3566 Development Board","Hardware","Embedded Linux","A six-layer Rockchip Linux development board engineered around a compact mobile-device form factor with high-speed memory and storage.","RK3566,6-layer PCB,LPDDR4,eMMC,Embedded Linux","RK3566%20Custom%20Development%20Board/f757f194b2ff422c9121f6f13c46d9ae.jpg","RK3566%20Custom%20Development%20Board.html"],
["RK3568 AMOLED Tablet","Hardware","Embedded computing","A compact Android and Linux tablet with a 3.92-inch high-resolution AMOLED touch display, wireless connectivity, and expandable storage.","RK3568,Android,Embedded Linux,AMOLED,PCB Design","RK3568%20small%20tablet%20with%20AMOLED%20screen/920129874b97484982e46e9685c867b8.jpg","RK3568%20small%20tablet%20with%20AMOLED%20screen.html"],
["RV1106 AI Camera","AI","Edge vision","A compact AI camera platform with local neural processing, an LVGL touch interface, wireless connectivity, and flexible flash storage.","RV1106,Embedded Linux,LVGL,NPU,PCB Design","RV1106%20AI%20Camera/cover.png","RV1106%20AI%20Camera.html"],
["ZYNQ7020 Core & RF Modules","Hardware","FPGA · RF systems","A custom ZYNQ7020 core board and collection of high-speed ADC, DAC, DDS, and PLL modules for RF experimentation.","ZYNQ7020,FPGA,Vivado,ADC/DAC,RF Design","ZYNQ7020%20Core%20&%20RF%20Modules/Zynq7020_Core.png","ZYNQ7020%20Core%20&%20RF%20Modules.html"]];
const projects=document.querySelector("#projects"),more=document.querySelector("#more"),filters=[...document.querySelectorAll(".filters button")],modal=document.querySelector("#project-modal");let active="All",expanded=false;
function render(){const list=data.filter(p=>active==="All"||p[1]===active);projects.innerHTML=list.map((p,i)=>`<button class="card ${!expanded&&i>=8?'hidden':''}" data-i="${data.indexOf(p)}" aria-label="Open ${p[0]}"><div class="card-media"><img loading="lazy" src="${base+p[5]}" alt="${p[0]}"><span class="card-num">${String(i+1).padStart(2,"0")}</span></div><div class="card-copy"><span>${p[2]}</span><h3>${p[0]}</h3><p>${p[3]}</p></div></button>`).join("");more.hidden=list.length<=8;more.textContent=expanded?"Show fewer projects −":"Show all projects +";document.querySelectorAll(".card").forEach(c=>c.onclick=()=>openProject(data[c.dataset.i]))}
function openProject(p){modal.querySelector("img").src=base+p[5];modal.querySelector("img").alt=p[0];modal.querySelector(".modal-label").textContent=p[2];modal.querySelector("h2").textContent=p[0];modal.querySelector(".modal-description").textContent=p[3];modal.querySelector(".skills").innerHTML=p[4].split(",").map(x=>`<span>${x}</span>`).join("");modal.querySelector(".modal-link").href=base+p[6];modal.showModal();document.body.classList.add("lock")}
filters.forEach(b=>b.onclick=()=>{filters.forEach(x=>x.classList.remove("active"));b.classList.add("active");active=b.dataset.filter;expanded=false;render()});more.onclick=()=>{expanded=!expanded;render()};modal.querySelector(".close").onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};modal.onclose=()=>document.body.classList.remove("lock");render();
